In [1]:
%load_ext autoreload
%autoreload 2

from src import *

In [2]:
df_maisons_parquet = pd.read_parquet(ROOTDIR / 'data' / 'interim' / 'indicateurs-loyers-maisons.parquet')
df_maisons_parquet.head()

,id_zone,INSEE,LIBGEO,DEP,REG,EPCI,TYPPRED,loypredm2,lwr.IPm2,upr.IPm2,R2adj,Nbobs_maille,NBobs_commune
0,1131,1001,L'Abergement-Clémenciat,1,84,200069193,maille,8.191701,6.585771,10.189234,0.730537,586,13
1,364,1002,L'Abergement-de-Varey,1,84,240100883,maille,7.441199,5.672105,9.762062,0.708215,643,18
2,806,1004,Ambérieu-en-Bugey,1,84,240100883,commune,8.411184,6.291932,11.244244,0.728004,610,465
3,501,1005,Ambérieux-en-Dombes,1,84,200042497,maille,9.039551,6.861075,11.909720,0.677777,569,53
4,459,1006,Ambléon,1,84,200040350,maille,8.058265,6.438140,10.086086,0.744074,1641,9

In [3]:
df_appartements_parquet = pd.read_parquet(ROOTDIR / 'data' / 'interim' / 'indicateurs-loyers-appartements.parquet')
df_appartements_parquet.head()

,id_zone,INSEE,LIBGEO,DEP,REG,EPCI,TYPPRED,loypredm2,lwr.IPm2,upr.IPm2,R2adj,NBobs_maille,NBobs_commune
0,2362,1001,L'Abergement-Clémenciat,1,84,200069193,maille,9.372335,7.409664,11.854880,0.774249,701,2
1,2010,1002,L'Abergement-de-Varey,1,84,240100883,maille,8.635552,6.721078,11.095358,0.719599,861,0
2,1456,1004,Ambérieu-en-Bugey,1,84,240100883,commune,10.074507,7.865307,12.904225,0.670161,2156,2156
3,2362,1005,Ambérieux-en-Dombes,1,84,200042497,maille,9.372335,7.409664,11.854880,0.774249,701,81
4,2055,1006,Ambléon,1,84,200040350,maille,8.966955,7.101593,11.322287,0.752823,842,3

# Data Exploration

## Exploration of the datasets

In [4]:
df_appartements_parquet.shape

(35441, 13)

In [5]:
df_maisons_parquet.shape

(35441, 13)

In [6]:
df_appartements_parquet.head()

,id_zone,INSEE,LIBGEO,DEP,REG,EPCI,TYPPRED,loypredm2,lwr.IPm2,upr.IPm2,R2adj,NBobs_maille,NBobs_commune
0,2362,1001,L'Abergement-Clémenciat,1,84,200069193,maille,9.372335,7.409664,11.854880,0.774249,701,2
1,2010,1002,L'Abergement-de-Varey,1,84,240100883,maille,8.635552,6.721078,11.095358,0.719599,861,0
2,1456,1004,Ambérieu-en-Bugey,1,84,240100883,commune,10.074507,7.865307,12.904225,0.670161,2156,2156
3,2362,1005,Ambérieux-en-Dombes,1,84,200042497,maille,9.372335,7.409664,11.854880,0.774249,701,81
4,2055,1006,Ambléon,1,84,200040350,maille,8.966955,7.101593,11.322287,0.752823,842,3

In [7]:
df_maisons_parquet.head()

,id_zone,INSEE,LIBGEO,DEP,REG,EPCI,TYPPRED,loypredm2,lwr.IPm2,upr.IPm2,R2adj,Nbobs_maille,NBobs_commune
0,1131,1001,L'Abergement-Clémenciat,1,84,200069193,maille,8.191701,6.585771,10.189234,0.730537,586,13
1,364,1002,L'Abergement-de-Varey,1,84,240100883,maille,7.441199,5.672105,9.762062,0.708215,643,18
2,806,1004,Ambérieu-en-Bugey,1,84,240100883,commune,8.411184,6.291932,11.244244,0.728004,610,465
3,501,1005,Ambérieux-en-Dombes,1,84,200042497,maille,9.039551,6.861075,11.909720,0.677777,569,53
4,459,1006,Ambléon,1,84,200040350,maille,8.058265,6.438140,10.086086,0.744074,1641,9

## Missing values

In [8]:
df_appartements_parquet.isna().any()

id_zone          False
INSEE            False
LIBGEO           False
DEP              False
REG              False
EPCI             False
TYPPRED          False
loypredm2        False
lwr.IPm2         False
upr.IPm2         False
R2adj            False
NBobs_maille     False
NBobs_commune    False
dtype: bool

In [9]:
df_maisons_parquet.isna().any()

id_zone          False
INSEE            False
LIBGEO           False
DEP              False
REG              False
EPCI             False
TYPPRED          False
loypredm2        False
lwr.IPm2         False
upr.IPm2         False
R2adj            False
Nbobs_maille     False
NBobs_commune    False
dtype: bool

## Types

In [10]:
df_appartements_parquet.dtypes

id_zone           object
INSEE             object
LIBGEO            object
DEP               object
REG                int64
EPCI              object
TYPPRED           object
loypredm2        float64
lwr.IPm2         float64
upr.IPm2         float64
R2adj            float64
NBobs_maille       int64
NBobs_commune      int64
dtype: object

In [11]:
df_maisons_parquet.dtypes

id_zone           object
INSEE             object
LIBGEO            object
DEP               object
REG                int64
EPCI              object
TYPPRED           object
loypredm2        float64
lwr.IPm2         float64
upr.IPm2         float64
R2adj            float64
Nbobs_maille       int64
NBobs_commune      int64
dtype: object

id_zone, INSEE, DEP and EPCI are of type **object** but when we look at the data using head() it looks like they should be **numerical**.

In [12]:
# list all unique values for id_zone
unique_id_zone_appartements = df_appartements_parquet['id_zone'].unique()
for i in unique_id_zone_appartements:
    if not i.isnumeric():
        print(i)

9_9713
6_9713
7_9713
13_9713
14_9713
4_9713
12_9713
5_9713
15_9713
8_9713
3_9713
10_9713
0_9713
1_9713
11_9713
2_9713

In [13]:
# list all unique values for id_zone
unique_id_zone_maisons = df_maisons_parquet['id_zone'].unique()
for i in unique_id_zone_maisons:
    if not i.isnumeric():
        print(i)

10_9713
17_9713
8_9713
16_9713
15_9713
4_9713
13_9713
5_9713
9_9713
3_9713
11_9713
7_9713
6_9713
14_9713
1_9713
12_9713
2_9713
0_9713

In [14]:
# list all unique values for INSEE
unique_insee_appartements = df_appartements_parquet['INSEE'].unique()
for i in unique_insee_appartements:
    if not i.isnumeric():
        print(i)

2A001
2A004
2A006
2A008
2A011
2A014
2A017
2A018
2A019
2A021
2A022
2A024
2A026
2A027
2A028
2A031
2A032
2A035
2A038
2A040
2A041
2A048
2A056
2A060
2A061
2A062
2A064
2A065
2A066
2A070
2A071
2A085
2A089
2A090
2A091
2A092
2A094
2A098
2A099
2A100
2A103
2A104
2A108
2A114
2A115
2A117
2A118
2A119
2A127
2A128
2A129
2A130
2A131
2A132
2A133
2A139
2A141
2A142
2A144
2A146
2A154
2A158
2A160
2A163
2A174
2A181
2A186
2A189
2A191
2A196
2A197
2A198
2A200
2A203
2A204
2A209
2A211
2A212
2A215
2A228
2A232
2A240
2A247
2A249
2A253
2A254
2A258
2A259
2A262
2A266
2A268
2A269
2A270
2A271
2A272
2A276
2A278
2A279
2A282
2A284
2A285
2A288
2A295
2A300
2A308
2A310
2A312
2A322
2A323
2A324
2A326
2A330
2A331
2A336
2A345
2A348
2A349
2A351
2A357
2A358
2A359
2A360
2A362
2A363
2B002
2B003
2B005
2B007
2B009
2B010
2B012
2B013
2B015
2B016
2B020
2B023
2B025
2B029
2B030
2B033
2B034
2B036
2B037
2B039
2B042
2B043
2B045
2B046
2B047
2B049
2B050
2B051
2B052
2B053
2B054
2B055
2B057
2B058
2B059
2B063
2B067
2B068
2B069
2B072
2B073
2B074
2B075
2B077
2B078
2B079
2B080
2B081
2B082
2B083
2B084
2B086
2B087
2B088
2B093
2B095
2B096
2B097
2B101
2B102
2B105
2B106
2B107
2B109
2B110
2B111
2B112
2B113
2B116
2B120
2B121
2B122
2B123
2B124
2B125
2B126
2B134
2B135
2B136
2B137
2B138
2B140
2B143
2B145
2B147
2B148
2B149
2B150
2B152
2B153
2B155
2B156
2B157
2B159
2B161
2B162
2B164
2B165
2B166
2B167
2B168
2B169
2B170
2B171
2B172
2B173
2B175
2B176
2B177
2B178
2B179
2B180
2B182
2B183
2B184
2B185
2B187
2B188
2B190
2B192
2B193
2B194
2B195
2B199
2B201
2B202
2B205
2B206
2B207
2B208
2B210
2B213
2B214
2B216
2B217
2B218
2B219
2B220
2B221
2B222
2B223
2B224
2B225
2B226
2B227
2B229
2B230
2B231
2B233
2B234
2B235
2B236
2B238
2B239
2B241
2B242
2B243
2B244
2B245
2B246
2B248
2B250
2B251
2B252
2B255
2B256
2B257
2B260
2B261
2B263
2B264
2B265
2B267
2B273
2B274
2B275
2B277
2B280
2B281
2B283
2B286
2B287
2B289
2B290
2B291
2B292
2B293
2B296
2B297
2B298
2B299
2B301
2B302
2B303
2B304
2B305
2B306
2B307
2B309
2B311
2B313
2B314
2B315
2B316
2B317
2B318
2B319
2B320
2B321
2B327
2B328
2B329
2B332
2B333
2B334
2B335
2B337
2B338
2B339
2B340
2B341
2B342
2B343
2B344
2B346
2B347
2B350
2B352
2B353
2B354
2B355
2B356
2B361
2B364
2B365
2B366

In [15]:
# list all unique values for INSEE
unique_insee_maisons = df_maisons_parquet['INSEE'].unique()
for i in unique_insee_maisons:
    if not i.isnumeric():
        print(i)

2A001
2A004
2A006
2A008
2A011
2A014
2A017
2A018
2A019
2A021
2A022
2A024
2A026
2A027
2A028
2A031
2A032
2A035
2A038
2A040
2A041
2A048
2A056
2A060
2A061
2A062
2A064
2A065
2A066
2A070
2A071
2A085
2A089
2A090
2A091
2A092
2A094
2A098
2A099
2A100
2A103
2A104
2A108
2A114
2A115
2A117
2A118
2A119
2A127
2A128
2A129
2A130
2A131
2A132
2A133
2A139
2A141
2A142
2A144
2A146
2A154
2A158
2A160
2A163
2A174
2A181
2A186
2A189
2A191
2A196
2A197
2A198
2A200
2A203
2A204
2A209
2A211
2A212
2A215
2A228
2A232
2A240
2A247
2A249
2A253
2A254
2A258
2A259
2A262
2A266
2A268
2A269
2A270
2A271
2A272
2A276
2A278
2A279
2A282
2A284
2A285
2A288
2A295
2A300
2A308
2A310
2A312
2A322
2A323
2A324
2A326
2A330
2A331
2A336
2A345
2A348
2A349
2A351
2A357
2A358
2A359
2A360
2A362
2A363
2B002
2B003
2B005
2B007
2B009
2B010
2B012
2B013
2B015
2B016
2B020
2B023
2B025
2B029
2B030
2B033
2B034
2B036
2B037
2B039
2B042
2B043
2B045
2B046
2B047
2B049
2B050
2B051
2B052
2B053
2B054
2B055
2B057
2B058
2B059
2B063
2B067
2B068
2B069
2B072
2B073
2B074
2B075
2B077
2B078
2B079
2B080
2B081
2B082
2B083
2B084
2B086
2B087
2B088
2B093
2B095
2B096
2B097
2B101
2B102
2B105
2B106
2B107
2B109
2B110
2B111
2B112
2B113
2B116
2B120
2B121
2B122
2B123
2B124
2B125
2B126
2B134
2B135
2B136
2B137
2B138
2B140
2B143
2B145
2B147
2B148
2B149
2B150
2B152
2B153
2B155
2B156
2B157
2B159
2B161
2B162
2B164
2B165
2B166
2B167
2B168
2B169
2B170
2B171
2B172
2B173
2B175
2B176
2B177
2B178
2B179
2B180
2B182
2B183
2B184
2B185
2B187
2B188
2B190
2B192
2B193
2B194
2B195
2B199
2B201
2B202
2B205
2B206
2B207
2B208
2B210
2B213
2B214
2B216
2B217
2B218
2B219
2B220
2B221
2B222
2B223
2B224
2B225
2B226
2B227
2B229
2B230
2B231
2B233
2B234
2B235
2B236
2B238
2B239
2B241
2B242
2B243
2B244
2B245
2B246
2B248
2B250
2B251
2B252
2B255
2B256
2B257
2B260
2B261
2B263
2B264
2B265
2B267
2B273
2B274
2B275
2B277
2B280
2B281
2B283
2B286
2B287
2B289
2B290
2B291
2B292
2B293
2B296
2B297
2B298
2B299
2B301
2B302
2B303
2B304
2B305
2B306
2B307
2B309
2B311
2B313
2B314
2B315
2B316
2B317
2B318
2B319
2B320
2B321
2B327
2B328
2B329
2B332
2B333
2B334
2B335
2B337
2B338
2B339
2B340
2B341
2B342
2B343
2B344
2B346
2B347
2B350
2B352
2B353
2B354
2B355
2B356
2B361
2B364
2B365
2B366

In [16]:
# list all unique values for DEP
unique_dep_appartements = df_appartements_parquet['DEP'].unique()
for i in unique_dep_appartements:
    if not i.isnumeric():
        print(i)

2A
2B

In [17]:
# list all unique values for DEP
unique_dep_maisons = df_maisons_parquet['DEP'].unique()
for i in unique_dep_maisons:
    if not i.isnumeric():
        print(i)

2A
2B

In [18]:
# list all unique values for EPCI
unique_epci_appartements = df_appartements_parquet['EPCI'].unique()
for i in unique_epci_appartements:
    if not i.isnumeric():
        print(i)

ZZZZZZZZZ

In [19]:
# list all unique values for EPCI
unique_epci_maisons = df_appartements_parquet['EPCI'].unique()
for i in unique_epci_maisons:
    if not i.isnumeric():
        print(i)

ZZZZZZZZZ

The value ZZZZZZZZZ looks like a missing value, it would be interesting to change it into a missing value to then change the column EPCI into the type int.

In [20]:
df_appartements_parquet.loc[(df_appartements_parquet.EPCI == 'ZZZZZZZZZ'), ('EPCI')] = np.nan
df_maisons_parquet.loc[(df_maisons_parquet.EPCI == 'ZZZZZZZZZ'), ('EPCI')] = np.nan

In [21]:
df_maisons_parquet = df_maisons_parquet.astype({"EPCI": float})
df_appartements_parquet = df_appartements_parquet.astype({"EPCI": float})

In [22]:
df_maisons_parquet.dtypes

id_zone           object
INSEE             object
LIBGEO            object
DEP               object
REG                int64
EPCI             float64
TYPPRED           object
loypredm2        float64
lwr.IPm2         float64
upr.IPm2         float64
R2adj            float64
Nbobs_maille       int64
NBobs_commune      int64
dtype: object

In [23]:
df_appartements_parquet.dtypes

id_zone           object
INSEE             object
LIBGEO            object
DEP               object
REG                int64
EPCI             float64
TYPPRED           object
loypredm2        float64
lwr.IPm2         float64
upr.IPm2         float64
R2adj            float64
NBobs_maille       int64
NBobs_commune      int64
dtype: object

In [24]:
df_appartements_parquet.describe().T

,count,mean,std,min,25%,50%,75%,max
REG,35441.0,5.233219e+01,2.433489e+01,1.000000e+00,2.800000e+01,4.400000e+01,7.600000e+01,9.400000e+01
EPCI,35436.0,2.129978e+08,2.027473e+07,2.000002e+08,2.000659e+08,2.000696e+08,2.414009e+08,2.497401e+08
loypredm2,35441.0,9.008120e+00,2.015895e+00,5.375503e+00,7.676385e+00,8.603550e+00,9.829359e+00,3.665444e+01
lwr.IPm2,35441.0,7.084386e+00,1.705735e+00,3.644538e+00,5.936234e+00,6.738174e+00,7.803369e+00,2.567251e+01
upr.IPm2,35441.0,1.148164e+01,2.527111e+00,7.070505e+00,9.895651e+00,1.095122e+01,1.229992e+01,5.597586e+01
R2adj,35441.0,7.125973e-01,9.152336e-02,1.763090e-01,6.535208e-01,7.217185e-01,7.792664e-01,9.998267e-01
NBobs_maille,35441.0,1.054793e+03,2.298806e+03,4.670000e+02,6.550000e+02,8.530000e+02,1.086000e+03,2.008400e+05
NBobs_commune,35441.0,2.043820e+02,2.315567e+03,0.000000e+00,0.000000e+00,4.000000e+00,2.300000e+01,2.008400e+05

In [25]:
df_maisons_parquet.describe().T

,count,mean,std,min,25%,50%,75%,max
REG,35441.0,5.233219e+01,2.433489e+01,1.000000e+00,2.800000e+01,4.400000e+01,7.600000e+01,9.400000e+01
EPCI,35436.0,2.129978e+08,2.027473e+07,2.000002e+08,2.000659e+08,2.000696e+08,2.414009e+08,2.497401e+08
loypredm2,35441.0,7.461193e+00,1.930469e+00,4.896745e+00,6.240555e+00,7.022982e+00,8.111478e+00,3.808597e+01
lwr.IPm2,35441.0,5.738771e+00,1.359490e+00,2.970530e+00,4.817872e+00,5.492990e+00,6.339342e+00,3.023367e+01
upr.IPm2,35441.0,9.743636e+00,3.065522e+00,6.104875e+00,8.065604e+00,9.036894e+00,1.042585e+01,6.750169e+01
R2adj,35441.0,6.894364e-01,8.717857e-02,3.258324e-01,6.320671e-01,6.909515e-01,7.513317e-01,9.694828e-01
Nbobs_maille,35441.0,7.737432e+02,2.410572e+02,4.560000e+02,5.960000e+02,7.220000e+02,8.980000e+02,6.575000e+03
NBobs_commune,35441.0,4.043935e+01,1.355043e+02,0.000000e+00,3.000000e+00,1.000000e+01,3.100000e+01,6.490000e+03

## Check values
We can check the number of unique values to see if something is wrong.

In [26]:
df_appartements_parquet.nunique().sort_values()

TYPPRED              3
REG                 17
DEP                100
EPCI              1262
NBobs_maille      1446
NBobs_commune     1694
id_zone           2776
R2adj             2776
loypredm2         5564
lwr.IPm2          5564
upr.IPm2          5564
LIBGEO           33082
INSEE            35441
dtype: int64

In [27]:
df_maisons_parquet.nunique().sort_values()

TYPPRED              3
REG                 17
DEP                100
Nbobs_maille       691
NBobs_commune      744
EPCI              1262
id_zone           1855
R2adj             1855
loypredm2         4872
lwr.IPm2          4872
upr.IPm2          4872
LIBGEO           33082
INSEE            35441
dtype: int64

From the unique values nothing special is to be underlined. The TYPPRED has 3 unique values, as explained in the documentation of the dataset, it can be of value "commune", "epci" or "maille". The number of region is 17, in France it exists 18 regions, so the number is logic, and the same for the departments (100 for 101 in total).

In [28]:
# list all unique values for TYPPRED
unique_typpred_appartements = df_appartements_parquet['TYPPRED'].unique()
unique_typpred_appartements

array(['maille', 'commune', 'epci'], dtype=object)

In [29]:
# list all unique values for TYPPRED
unique_typpred_maisons = df_maisons_parquet['TYPPRED'].unique()
unique_typpred_maisons

array(['maille', 'commune', 'epci'], dtype=object)

In [30]:
# list all unique values for REG
unique_reg_appartements = df_appartements_parquet['REG'].unique()
unique_reg_appartements

array([84, 32, 93, 44, 76, 28, 75, 24, 27, 53, 94, 52, 11,  1,  2,  3,  4])

In [31]:
# list all unique values for REG
unique_reg_maisons = df_maisons_parquet['REG'].unique()
unique_reg_maisons

array([84, 32, 93, 44, 76, 28, 75, 24, 27, 53, 94, 52, 11,  1,  2,  3,  4])

We can see that each region has a precise code number but it is not detailed in the documentation how this number has been chosen.

## Understanding the region code

We can try to guess by looking at the cities that are in the region.

### Region 32

In [32]:
mask = df_maisons_parquet.REG == 32
region32 = df_maisons_parquet[mask]
region32.shape

(3809, 13)

In [33]:
region32_cities = region32['LIBGEO'].unique()
region32_cities

array(['Abbécourt', 'Achery', 'Acy', ..., 'Yzengremer', 'Yzeux', 'Yonval'],
      dtype=object)

In [34]:
region32_cities.size

3747

In [35]:
arr = np.arange(1, 3747, 300)
arr

array([   1,  301,  601,  901, 1201, 1501, 1801, 2101, 2401, 2701, 3001,
       3301, 3601])

In [36]:
for i in arr:
    print(region32_cities[i])

Achery
La Flamengrie
Proisy
Boussières-sur-Sambre
Mortagne-du-Nord
Beauvoir
Lieuvillers
Villeneuve-les-Sablons
Écoust-Saint-Mein
Nédon
La Capelle-lès-Boulogne
Forceville
Rethonvillers

By checking by hand some of the cities in the region with the code **32**, it is possible to conclude that the region 32 corresponds to the region **Hauts-de-France**.

### Region 84

In [37]:
mask = df_maisons_parquet.REG == 84
region84 = df_maisons_parquet[mask]
region84.shape

(4103, 13)

In [38]:
region84_cities = region84['LIBGEO'].unique()
region84_cities

array(["L'Abergement-Clémenciat", "L'Abergement-de-Varey",
       'Ambérieu-en-Bugey', ..., 'Vovray-en-Bornes', 'Vulbens', 'Yvoire'],
      dtype=object)

The region **84** corresponds to **Auvergne-Rhône-Alpes**.

### Region code conclusion

Using the name of the region and the code of the region, I found out that the code correspond to the code provided by the INSEE, here is the list of the regions:

01,Guadeloupe
02,Martinique
03,Guyane
04,La Réunion
06,Mayotte
11,Île-de-France
24,Centre-Val de Loire
27,Bourgogne-Franche-Comté
28,Normandie
32,Hauts-de-France
44,Grand Est
52,Pays de la Loire
53,Bretagne
75,Nouvelle-Aquitaine
76,Occitanie
84,Auvergne-Rhône-Alpes
93,Provence-Alpes-Côte d'Azur
94,Corse

It is possible to add the name of the regions directly in the dataframe. It can be not so interesting to do it, but it is interesting to practice with the dataframe.

In [39]:
dict_region = {
    "1":"Guadeloupe",
    "2":"Martinique",
    "3":"Guyane",
    "4":"La Réunion",
    "6":"Mayotte",
    "11":"Île-de-France",
    "24":"Centre-Val de Loire",
    "27":"Bourgogne-Franche-Comté",
    "28":"Normandie",
    "32":"Hauts-de-France",
    "44":"Grand Est",
    "52":"Pays de la Loire",
    "53":"Bretagne",
    "75":"Nouvelle-Aquitaine",
    "76":"Occitanie",
    "84":"Auvergne-Rhône-Alpes",
    "93":"Provence-Alpes-Côte d'Azur",
    "94":"Corse"
}

In [40]:
# Convert the column REG into str to be able to map with the dictionary.
df_maisons_reg_str = df_maisons_parquet.astype({"REG": str})
df_maisons_parquet_reg = df_maisons_parquet
df_maisons_parquet_reg['REG_name'] = df_maisons_reg_str['REG'].map(dict_region)

del df_maisons_reg_str

df_maisons_parquet_reg

,id_zone,INSEE,LIBGEO,DEP,REG,EPCI,TYPPRED,loypredm2,lwr.IPm2,upr.IPm2,R2adj,Nbobs_maille,NBobs_commune,REG_name
0,1131,1001,L'Abergement-Clémenciat,1,84,200069193.0,maille,8.191701,6.585771,10.189234,0.730537,586,13,Auvergne-Rhône-Alpes
1,364,1002,L'Abergement-de-Varey,1,84,240100883.0,maille,7.441199,5.672105,9.762062,0.708215,643,18,Auvergne-Rhône-Alpes
2,806,1004,Ambérieu-en-Bugey,1,84,240100883.0,commune,8.411184,6.291932,11.244244,0.728004,610,465,Auvergne-Rhône-Alpes
3,501,1005,Ambérieux-en-Dombes,1,84,200042497.0,maille,9.039551,6.861075,11.909720,0.677777,569,53,Auvergne-Rhône-Alpes
4,459,1006,Ambléon,1,84,200040350.0,maille,8.058265,6.438140,10.086086,0.744074,1641,9,Auvergne-Rhône-Alpes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35436,331,97420,Sainte-Suzanne,974,4,249740119.0,commune,9.635883,7.107986,13.062805,0.616186,514,514,La Réunion
35437,1079,97421,Salazie,974,4,249740093.0,maille,8.563707,6.404036,11.451696,0.630157,644,81,La Réunion
35438,329,97422,Le Tampon,974,4,249740085.0,commune,10.139715,7.338143,14.010877,0.610397,2733,2733,La Réunion
35439,1079,97423,Les Trois-Bassins,974,4,249740101.0,commune,9.677387,7.237465,12.939863,0.630157,644,208,La Réunion
35440,1079,97424,Cilaos,974,4,249740077.0,commune,7.607132,5.686818,10.175893,0.630157,644,114,La Réunion

In [41]:
del df_maisons_parquet_reg